# Generated by Django 3.2.4 on 2022-03-15 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quiz_name', models.TextField()),
                ('quiz_description', models.TextField()),
                ('No_Of_Questions', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
    ]
